require:
  - solidus_dev_support/rubocop

AllCops:
  Exclude:
    - sandbox/**/*
    - spec/dummy/**/*
    - vendor/bundle/**/*

Style/FrozenStringLiteralComment:
  Exclude:
    - spec/**/*
    - db/migrate/**/*
    - bin/**/*
