require:
  - solidus_dev_support/rubocop

AllCops:
  Exclude:
    - sandbox/**/*
    - spec/dummy/**/*
    - vendor/bundle/**/*

Metrics/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Exclude:
    - spec/**/*
    - db/migrate/**/*
    - bin/**/*
